### ISSUE TITLE
Get all analysis code of a specific application

### ISSUE THREAD

**Issue by JoseGCheca** [kiuwan/java-api-client#1]
Is there any way to request all the analysis codes of a specific application as well as the last analysis code?

Thank you for your support.

José

**Comment by kiuwan** [comment]
Hi José,
currently we do not have any mechanism to retrieve all analysis codes of a apecific application. 
However, there is an API to retrieve the last analysis result of an application that extracts the analysis code too. You can see reference in https://www.kiuwan.com/docs/display/K5/Results+of+analysis, in section called "Get application analysis". The first option "GET /apps/:appName" can be useful to you.

**Comment by JoseGCheca** [comment]
Hi,

Thank you for your response. 

I knew there was an API to retrieve the last analysis but in case you need previous analysis codes, there isn't any way of getting the previous codes unless you had stored them when the app using kiuwan API was used by the very first time (If you use the API and an application has already been uploaded, previous analysis codes are not available).

Thank you.

José

**Comment by kiuwan** [comment]
OK, we understand your case.
We will open a proposal to add this feature in the future.
When the feature is available, we will notify you.

**Comment by JoseGCheca** [comment]
Hi, 

I appreciate it very much.

Thank you again for your support.

José

**Comment by kiuwan** [comment]
Hi José, we have published a new endpoint that retrieves the list of analyses for an application.
Here is the sample code: https://github.com/kiuwan/java-api-client/blob/master/src/main/java/com/kiuwan/client/examples/ListAnalyses.java

And here you can find the detailed documentation: https://www.kiuwan.com/docs/display/K5/Results+of+analysis,  in the section 'List analyses'.
